Repository DeoxysTheGod/Journal-Interne-IUT, pull requests merged in 2024-03, with the labels that each got.

#2 Feature/navbar
  .idea/.gitignore
  doc/pull-request.md
  res/img/amu-blue.svg
  res/img/amu-white@2x.png
  src/index.html
  src/style.css
Labels: feature

#11 Réglage des chemins relatifs
  README.md
  index.html
  pages/etudier-a-iut.html
  pages/journal-page.html
  pages/pk-nous-choisir.html
  pages/profs.html
  pages/vie-etudiante.html
  script/page.js
Labels: fix

#12 fix path
  README.md
  index.html
  pages/etudier-a-iut.html
  pages/journal-page.html
  pages/pk-nous-choisir.html
  pages/profs.html
  pages/vie-etudiante.html
  script/page.js
Labels: fix

#13 Réglage des chemins relatifs
  index.html
  pages/etudier-a-iut.html
  pages/journal-page.html
  pages/pk-nous-choisir.html
  pages/profs.html
  pages/vie-etudiante.html
Labels: fix

#16 Réglage des chemins relatifs
  .idea/.gitignore
  pages/erasmus.html
  res/img/erasmus.jpg
Labels: fix

#17 Fix/loading pages
  script/page.js
Labels: fix

#20 fix startup page
  script/page.js
Labels: fix

#22 Feature/more article
  index.html
  pages/apres-but.html
  pages/av-vie-etu.html
  pages/bde.html
  pages/erasmus.html
  pages/journal-page.html
  pages/sae.html
  res/img/erasmus/partenaires.png
  res/img/sae/fiche-1-p1.png
  res/img/sae/fiche-1-p2.png
  res/img/sae/fiche-2-p1.png
  res/img/sae/fiche-2-p2.png
  res/img/sae/fiche-3-p1.png
  res/img/sae/fiche-3-p2.png
  res/img/sae/fiche-4-p1.png
  res/img/sae/fiche-4-p2.png
  res/img/sae/fiche-5-p1.png
  res/img/sae/fiche-5-p2.png
  res/img/sae/fiche-6-p1.png
  res/img/sae/fiche-6-p2.png
  res/img/sae/fiche-7-p1.png
  res/img/sae/fiche-7-p2.png
  res/img/sae/fiche-8-p1.png
  res/img/sae/fiche-8-p2.png
  script/page.js
  styles/style.css
Labels: improvement
